#!/usr/bin/env tsx
/**
 * Prebuild script: reads .agents/ content and generates src/registry.ts
 * This makes the npm package self-contained (no filesystem access needed).
 */
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const AGENTS_ROOT = join(__dirname, "..", "..", ".agents");
const OUTPUT = join(__dirname, "..", "src", "registry.ts");

async function readMdFiles(dir: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  const files = await readdir(dir);
  for (const f of files) {
    if (!f.endsWith(".md")) continue;
    result[f.replace(/\.md$/, "")] = await readFile(join(dir, f), "utf-8");
  }
  return result;
}

async function readSkillDirs(dir: string): Promise<Record<string, { skill: string; subFiles: Record<string, string>; hasScripts: boolean }>> {
  const result: Record<string, { skill: string; subFiles: Record<string, string>; hasScripts: boolean }> = {};
  const entries = await readdir(dir);

  for (const entry of entries) {
    const skillDir = join(dir, entry);
    const info = await stat(skillDir);
    if (!info.isDirectory()) continue;

    const skillFile = join(skillDir, "SKILL.md");
    let skillContent: string;
    try {
      skillContent = await readFile(skillFile, "utf-8");
    } catch {
      continue;
    }

    const subFiles: Record<string, string> = {};
    const dirFiles = await readdir(skillDir);
    for (const f of dirFiles) {
      if (f === "SKILL.md" || !f.endsWith(".md")) continue;
      subFiles[f] = await readFile(join(skillDir, f), "utf-8");
    }

    let hasScripts = false;
    try {
      const scriptsInfo = await stat(join(skillDir, "scripts"));
      hasScripts = scriptsInfo.isDirectory();
    } catch { /* no scripts */ }

    result[entry] = { skill: skillContent, subFiles, hasScripts };
  }
  return result;
}

async function main() {
  console.log("[bundle-content] Reading .agents/ ...");

  const [agents, skills, workflows, architecture, instructions] = await Promise.all([
    readMdFiles(join(AGENTS_ROOT, "agents")),
    readSkillDirs(join(AGENTS_ROOT, "skills")),
    readMdFiles(join(AGENTS_ROOT, "workflows")),
    readFile(join(AGENTS_ROOT, "ARCHITECTURE.md"), "utf-8"),
    readFile(join(AGENTS_ROOT, "INSTRUCTIONS.md"), "utf-8"),
  ]);

  const agentCount = Object.keys(agents).length;
  const skillCount = Object.keys(skills).length;
  const workflowCount = Object.keys(workflows).length;

  const code = `// AUTO-GENERATED by scripts/bundle-content.ts — DO NOT EDIT
// ${agentCount} agents, ${skillCount} skills, ${workflowCount} workflows

export const EMBEDDED_AGENTS: Record<string, string> = ${JSON.stringify(agents, null, 2)};

export const EMBEDDED_SKILLS: Record<string, { skill: string; subFiles: Record<string, string>; hasScripts: boolean }> = ${JSON.stringify(skills, null, 2)};

export const EMBEDDED_WORKFLOWS: Record<string, string> = ${JSON.stringify(workflows, null, 2)};

export const EMBEDDED_ARCHITECTURE: string = ${JSON.stringify(architecture)};

export const EMBEDDED_INSTRUCTIONS: string = ${JSON.stringify(instructions)};
`;

  await writeFile(OUTPUT, code, "utf-8");
  console.log(`[bundle-content] Generated src/registry.ts (${agentCount} agents, ${skillCount} skills, ${workflowCount} workflows)`);
}

main().catch((err) => {
  console.error("[bundle-content] FATAL:", err);
  process.exit(1);
});
